@startuml

entity Employees {
    employee id
    --
    * name
    category_id
}

entity Employees_task {
    task id
    employee id
    --
    customer_name_todo
    customer_email_todo
    order_date_todo
}

entity Task {
    Task ID
    --
    Name
    Status
 }

Employees ||--o{ Employees_task
Task ||--|{ Employees_task


@enduml