@startuml

actor User
participant WebBrowser

box Java Server
    participant HttpServer
    participant EmployeeListController
    participant EmployeeDao
end box

database PostgreSQL

User -> WebBrowser: List employees
WebBrowser -> HttpServer: /index.html
WebBrowser <-- HttpServer: <html>...<script>fetch()</html>
WebBrowser --> HttpServer: /api/employees
HttpServer --> HttpServer: controllers.get("/api/employees")
HttpServer -> EmployeeDao: List()
EmployeeDao -> PostgreSQL: SELECT * FROM EMPLOYEES
EmployeeDao <-- PostgreSQL: ResultSet
HttpServer <-- EmployeeDao: List<employees>
WebBrowser <-- HttpServer: <li>elise Easter elise@mail</li><li>..</li>
User <-- WebBrowser: List of employees

@enduml